"""add_user_id_to_testimonials

Revision ID: baa036ff4db3
Revises: 81d9609fffca
Create Date: 2024-11-23 19:45:12.021449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'baa036ff4db3'
down_revision: Union[str, None] = '81d9609fffca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testimonials', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'testimonials', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'testimonials', type_='foreignkey')
    op.drop_column('testimonials', 'user_id')
    # ### end Alembic commands ###
